import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
        <meta name = "viewport" content="device-height, initial-scale=1.0, viewport-fit=cover"/>
      </head> 
       <html lang="en" className="w-[430px] h-[932px]">
        <body className={`${inter.className} w-[430px] h-[932px] flex justify-center items-center place-content-center justify-items-center align-middle overf `}>
          <main className="w-full h-full relative bg-[#EEE8F0]   flex flex-col "> 
              {children}
          </main>
        </body>
      </html>
    </>

  );
}
